Repository chingu-x/chingu-frontend, pull requests merged in 2018-09, with the labels that each got.

#46 Fix newsfeed warnings
  build_fragments.js
  package-lock.json
  package.json
  src/components/FeedPortal/components/SideBar.jsx
  src/components/FeedPortal/components/TeamCard.jsx
  src/fragmentTypes.json
  src/index.js
Labels: high priority, review

#49 Refactor Header
  src/components/Header/Header.js
  src/components/Header/userBaseQuery.js
Labels: review

#59 Fix github auth attempt error while logged in
  src/App.js
  src/components/Login/index.jsx
Labels: bug, review

#61 Refactor/#60 team standup use standup
  src/App.js
  src/components/FeedPortal/components/ChinguCards.jsx
  src/components/FeedPortal/components/TeamCard.jsx
  src/components/TeamStandup/index.jsx
Labels: review

#77 add public_repo scope to github auth redirect link
  src/components/Login/components/GithubLoginModal.jsx
Labels: review

#81 Refactor/#78 update dynamic forms
  build_fragments.js
  src/components/DynamicForm/components/DynamicFormContainer.jsx
  src/components/DynamicForm/components/DynamicFormMaker/QuestionComponents/dropdown.jsx
  src/components/DynamicForm/components/DynamicFormWrapper.jsx
  src/components/DynamicForm/components/utilities.js
Labels: review

#50 Add projects to UserProfile
  src/App.js
  src/components/FeedPortal/components/TeamCard.jsx
  src/components/FeedPortal/components/TeamCard.scss
  src/components/UserProfile/UserProfile.scss
  src/components/UserProfile/UserSideBar.jsx
  src/components/UserProfile/graphql/profileQuery.js
  src/components/UserProfile/index.jsx
  src/components/utilities/EditableTextField.jsx
Labels: review

#83 PopupMenu
  src/components/Header/Header.js
  src/components/utilities/PopupMenu.jsx
  src/styles/layout/_header.scss
Labels: review

#74 Redirect nonexistent project path to /projects
  src/App.js
  src/components/ProjectShowcase/index.jsx
Labels: REVIEW

#96 Feature/#95 non auth ticketbox
  src/App.js
  src/components/FeedPortal/components/TeamCard.jsx
  src/components/FeedPortal/components/TeamCard.scss
  src/components/Landing/components/landingBarRenderers.js
  src/components/ProjectShowcase/components/ImageGallery/Thumbnail.jsx
  src/components/Ticketbox/components/Help/HelpPageSearch.jsx
  src/components/Ticketbox/components/Help/index.jsx
  src/components/Ticketbox/index.jsx
  src/components/utilities/PopupMenu.jsx
Labels: REVIEW

#99 Switch chevron direction on expansionPanel open/close toggle
  src/components/HelpPage/Help.scss
  src/components/HelpPage/index.jsx
Labels: REVIEW

#103 Refactor/#102 disable help search
  src/App.js
  src/components/Footer/Footer.js
  src/components/Ticketbox/components/BugSuggestion.jsx
  src/components/Ticketbox/components/Feedback/BugSuggestion.jsx
  src/components/Ticketbox/components/Feedback/BugSuggestionQA.js
  src/components/Ticketbox/components/Help/HelpOptions.jsx
  src/components/Ticketbox/components/Help/TeamHelp.jsx
  src/components/Ticketbox/components/Help/index.jsx
  src/components/Ticketbox/index.jsx
Labels: REVIEW

#100 Ticketbox sprint cleanup
  src/components/AllProjects/index.jsx
  src/components/DynamicForm/DynamicForm.scss
  src/components/FeedPortal/components/FeedItem.jsx
  src/components/FeedPortal/components/SideBar.jsx
  src/components/FeedPortal/index.jsx
  src/components/Header/Header.js
  src/components/HelpPage/help-qa.data.js
  src/components/Landing/components/LandingTop.jsx
  src/components/Loader/index.jsx
  src/components/Login/components/GithubLoginModal.jsx
  src/components/Ticketbox/Ticketbox.scss
  src/components/Ticketbox/components/Help/HelpOptions.jsx
  src/components/Ticketbox/components/Help/HelpPageSearch.jsx
  src/components/Ticketbox/components/Help/TeamHelp.jsx
  src/components/Ticketbox/components/Help/TeamHelpQA.js
  src/components/Ticketbox/components/Help/index.jsx
  src/components/UserProfile/index.jsx
  src/components/VoyageApplication/index.jsx
  src/components/VoyageCard/VoyageCard.js
  src/components/VoyagePortal/index.jsx
  src/components/utilities/PopupMenu.jsx
  src/components/utilities/Request.jsx
Labels: REVIEW, STILL WORKING
